# Generated by Django 2.2.4 on 2019-08-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, max_length=2048, null=True, verbose_name='内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'bv_comment',
            },
        ),
    ]
