# Generated by Django 2.2.4 on 2019-08-06 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='detail',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='评论的视频'),
        ),
    ]
