# Generated by Django 2.2.4 on 2019-08-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('video', '0001_initial'),
        ('msgboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgboard',
            name='stu',
            field=models.ForeignKey(on_delete=None, to='users.Student', verbose_name='留言的学生'),
        ),
        migrations.AddField(
            model_name='msgboard',
            name='video',
            field=models.ForeignKey(on_delete=None, to='video.Video', verbose_name='哪一个视频'),
        ),
    ]
