# Generated by Django 2.2.4 on 2019-08-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, verbose_name='分类名称')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '视频分类',
                'verbose_name_plural': '视频分类',
                'db_table': 'bv_video_category',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名', max_length=128, verbose_name='视频标题')),
                ('video_path', models.FileField(upload_to='', verbose_name='视频地址')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('categories', models.ForeignKey(on_delete=None, to='video.VideoCategory', verbose_name='分类')),
                ('uploader', models.ForeignKey(on_delete=None, to='users.Teacher', verbose_name='上传者')),
            ],
            options={
                'verbose_name': '视频信息',
                'verbose_name_plural': '视频信息',
                'db_table': 'bv_video',
            },
        ),
    ]
